### ISSUE TITLE
paper name

### ISSUE THREAD

**Issue by amiltonwong** [lhanaf/FlashFusion#1]
Hi, @lhanaf ,

What's the paper name of this work "FlashFusion"?

**Comment by lhanaf** [comment]
Thanks for your attention!
For the related project page, please refer to: 
https://www.youtube.com/watch?v=wWpJJVycOos
or
www.luvision.net/FlashFusion

Best Regards
Lei Han

**Comment by amiltonwong** [comment]
Hi @lhanaf ,

Thanks for your reply. BTW, when will the paper and code be released?

**Comment by lhanaf** [comment]
Approximately before July, during the main conference of RSS.
